### ISSUE TITLE
KSS Config template option not working

### ISSUE THREAD

**Issue by devinle** [jonespen/kss-webpack-plugin#4]
Seems like with the newest version of KSS, it expects builder rather than template. I believe the template is expected to be a clone of the templates that ship with the latest KSS node module. Just thought I'd bring it up in case anyone else has the same issue. Works great for me now.

var KssConfig = {
  source: 'path/to/css_or_scss',
  template: 'path/to/template'
};

becomes

var KssConfig = {
  source: 'path/to/css_or_scss',
  builder: 'path/to/template'
};

**Comment by MartinMuzatko** [comment]
Yes this is correct, please change the property to builder, instead of template. Or at least document that (deprecation notice). @jonespen

**Comment by jonespen** [comment]
Cool! Feel free to submit a PR ;) 

Sendt fra min iPhone

**Comment by jonespen** [comment]
Solved by #5
