### ISSUE TITLE
Add support for Webpack 4

### ISSUE THREAD

**Issue by davecranwell-adestra** [jonespen/kss-webpack-plugin#7]
Note to self: examples of how to change to `.hooks` system visible here: https://github.com/danethurber/webpack-manifest-plugin/pull/118/files

**Comment by panuchka** [comment]
Any progress on this one? :) Would like to get rid of tapable warnings.

**Comment by jonascarlbaum** [comment]
I really like this plugin, but the `Tapable` warnings is getting annoying... ;)

**Comment by jonespen** [comment]
Really not using this anymore, so feel free to submit a PR :)

**Comment by ryuran** [comment]
OK since v1.50
